/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ofertaeducativa;

import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class Constantes implements Serializable {
    String RUTAMALLACURRICULARBASE = "";
    String RUTANOTASESTUDIANTES = "";

    String RUTAOFERTAEDUCATIVAHORARIOGRUPOS = "";
    String RUTAOFERTAEDUCATIVAHORARIODOCENTES = "";
    String RUTAOFERTAEDUCATIVACONTEOCORTES = "";
    String RUTAOFERTAEDUCATIVACREARSEGUIMIENTOS = "";
    String RUTAOFERTAEDUCATIVACRUZARCOMPARTIR = "";
    String RUTAOFERTAEDUCATIVACREARHORARIO = "";
    String CARPETASALIDAHORARIOGRUPOS = "";
    String CARPETASALIDAHORARIODOCENTES = "";
    String CARPETASALIDACONTEOCORTES = "";
    String CARPETASALIDAOFERTAEDUCATIVAPROYECCION="";
    String RUTAMALLACURRICULARBASECREARSEGUIMIENTOS = "";
    String RUTAMALLACURRICULARBASEPROYECCION = "";
    String RUTAMALLACURRICULARBASECREARHORARIO = "";
    String RUTAEXCELMATRICULASNRCBANNERCREARSEGUIMIENTO = "";
    String RUTAEXCELMATRICULASNRCBANNERCREARHORARIOS = "";
    String CARPETASALIDASEGUIMIENTOS = "";
    String PERIODOACTUAL = "";
    String RUTALIBROSEGUIMIENTOS = "";
    String RUTALIBROCUPOSESTIMADOS = "";
    String RUTALIBROMETASPRIMERSEMESTRES = "";
    String CARPETASALIDAOFERTAEDUCATIVA = "";
    String CARPETASALIDAHORARIOS = "";
    String PERIODOSIGUIENTE = "";
    String RUTALIBROFORMATOBELLO = "";
    String FECHAINICIOSEMESTRE = "";
    String FECHAFINALSEMESTRE = "";
    String FECHAINICIOLYJ = "";
    String FECHAINICIOLYM = "";
    String FECHAINICIOMYJ = "";
    String FECHAINICIOMIYVIP = "";
    String FECHAINICIOMIYVI = "";
    String FECHAINICIOSABADOD = "";
    String FECHAINICIOSABADOD2 = "";
    String FECHAINICIOSABADOT = "";
    String FECHAINICIOSABADOT2 = "";
    ArrayList<String> FECHASPROHIBIDAS;

    /**
     *
     * @param RUTAOFERTAEDUCATIVAHORARIOGRUPOS
     * @param RUTAOFERTAEDUCATIVAHORARIODOCENTES
     * @param RUTAOFERTAEDUCATIVACONTEOCORTES
     * @param RUTAOFERTAEDUCATIVACREARSEGUIMIENTOS
     * @param RUTAOFERTAEDUCATIVACRUZARCOMPARTIR
     * @param RUTAOFERTAEDUCATIVACREARHORARIO
     * @param CARPETASALIDAHORARIOGRUPOS
     * @param CARPETASALIDAHORARIODOCENTES
     * @param CARPETASALIDACONTEOCORTES
     * @param RUTAMALLACURRICULARBASECREARSEGUIMIENTOS
     * @param RUTAMALLACURRICULARBASEPROYECCION
     * @param RUTAMALLACURRICULARBASECREARHORARIO
     * @param RUTAEXCELMATRICULASNRCBANNERCREARSEGUIMIENTO
     * @param RUTAEXCELMATRICULASNRCBANNERCREARHORARIOS
     * @param CARPETASALIDASEGUIMIENTOS
     * @param PERIODOACTUAL
     * @param RUTALIBROSEGUIMIENTOS
     * @param RUTALIBROCUPOSESTIMADOS
     * @param RUTALIBROMETASPRIMERSEMESTRES
     * @param CARPETASALIDAOFERTAEDUCATIVA
     * @param CARPETASALIDAHORARIOS
     * @param PERIODOSIGUIENTE
     * @param RUTALIBROFORMATOBELLO
     * @param FECHAINICIOSEMESTRE
     */
    public Constantes(
            String RUTAMALLACURRICULARBASE,
            String RUTANOTASESTUDIANTES,
            String RUTAOFERTAEDUCATIVAHORARIOGRUPOS,
            String RUTAOFERTAEDUCATIVAHORARIODOCENTES,
            String RUTAOFERTAEDUCATIVACONTEOCORTES,
            String RUTAOFERTAEDUCATIVACREARSEGUIMIENTOS,
            String RUTAOFERTAEDUCATIVACRUZARCOMPARTIR,
            String RUTAOFERTAEDUCATIVACREARHORARIO,
            String CARPETASALIDAHORARIOGRUPOS,
            String CARPETASALIDAHORARIODOCENTES,
            String CARPETASALIDACONTEOCORTES,
            String CARPETASALIDAOFERTAEDUCATIVAPROYECCION,
            String RUTAMALLACURRICULARBASECREARSEGUIMIENTOS,
            String RUTAMALLACURRICULARBASEPROYECCION,
            String RUTAMALLACURRICULARBASECREARHORARIO,
            String RUTAEXCELMATRICULASNRCBANNERCREARSEGUIMIENTO,
            String RUTAEXCELMATRICULASNRCBANNERCREARHORARIOS,
            String CARPETASALIDASEGUIMIENTOS,
            String PERIODOACTUAL,
            String RUTALIBROSEGUIMIENTOS,
            String RUTALIBROCUPOSESTIMADOS,
            String RUTALIBROMETASPRIMERSEMESTRES,
            String CARPETASALIDAOFERTAEDUCATIVA,
            String CARPETASALIDAHORARIOS,
            String PERIODOSIGUIENTE,
            String RUTALIBROFORMATOBELLO,
            String FECHAINICIOSEMESTRE,
            String FECHAFINALSEMESTRE,
            String FECHAINICIOLYJ,
            String FECHAINICIOLYM,
            String FECHAINICIOMYJ,
            String FECHAINICIOMIYVIP,
            String FECHAINICIOMIYVI,
            String FECHAINICIOSABADOD,
            String FECHAINICIOSABADOD2,
            String FECHAINICIOSABADOT,
            String FECHAINICIOSABADOT2,
            ArrayList<String> FECHASPROHIBIDAS
    ) {
        this.RUTAOFERTAEDUCATIVAHORARIOGRUPOS = RUTAOFERTAEDUCATIVAHORARIOGRUPOS;
        this.RUTAOFERTAEDUCATIVAHORARIODOCENTES = RUTAOFERTAEDUCATIVAHORARIODOCENTES;
        this.RUTAOFERTAEDUCATIVACONTEOCORTES = RUTAOFERTAEDUCATIVACONTEOCORTES;
        this.RUTAOFERTAEDUCATIVACREARSEGUIMIENTOS = RUTAOFERTAEDUCATIVACREARSEGUIMIENTOS;
        this.RUTAOFERTAEDUCATIVACRUZARCOMPARTIR = RUTAOFERTAEDUCATIVACRUZARCOMPARTIR;
        this.RUTAOFERTAEDUCATIVACREARHORARIO = RUTAOFERTAEDUCATIVACREARHORARIO;
        this.CARPETASALIDAHORARIOGRUPOS = CARPETASALIDAHORARIOGRUPOS;
        this.CARPETASALIDAHORARIODOCENTES = CARPETASALIDAHORARIODOCENTES;
        this.CARPETASALIDACONTEOCORTES = CARPETASALIDACONTEOCORTES;
        this.CARPETASALIDAOFERTAEDUCATIVAPROYECCION = CARPETASALIDAOFERTAEDUCATIVAPROYECCION;
        this.RUTAMALLACURRICULARBASECREARSEGUIMIENTOS = RUTAMALLACURRICULARBASECREARSEGUIMIENTOS;
        this.RUTAMALLACURRICULARBASEPROYECCION = RUTAMALLACURRICULARBASEPROYECCION;
        this.RUTAMALLACURRICULARBASECREARHORARIO = RUTAMALLACURRICULARBASECREARHORARIO;
        this.RUTAEXCELMATRICULASNRCBANNERCREARSEGUIMIENTO = RUTAEXCELMATRICULASNRCBANNERCREARSEGUIMIENTO;
        this.RUTAEXCELMATRICULASNRCBANNERCREARHORARIOS = RUTAEXCELMATRICULASNRCBANNERCREARHORARIOS;
        this.CARPETASALIDASEGUIMIENTOS = CARPETASALIDASEGUIMIENTOS;
        this.PERIODOACTUAL = PERIODOACTUAL;
        this.RUTALIBROSEGUIMIENTOS = RUTALIBROSEGUIMIENTOS;
        this.RUTALIBROCUPOSESTIMADOS = RUTALIBROCUPOSESTIMADOS;
        this.RUTALIBROMETASPRIMERSEMESTRES = RUTALIBROMETASPRIMERSEMESTRES;
        this.CARPETASALIDAOFERTAEDUCATIVA = CARPETASALIDAOFERTAEDUCATIVA;
        this.CARPETASALIDAHORARIOS = CARPETASALIDAHORARIOS;
        this.PERIODOSIGUIENTE = PERIODOSIGUIENTE;
        this.RUTALIBROFORMATOBELLO = RUTALIBROFORMATOBELLO;
        this.FECHAINICIOSEMESTRE = FECHAINICIOSEMESTRE;
        this.FECHAFINALSEMESTRE = FECHAFINALSEMESTRE;
        this.FECHAINICIOLYJ = FECHAINICIOLYJ;
        this.FECHAINICIOLYM = FECHAINICIOLYM;
        this.FECHAINICIOMYJ = FECHAINICIOMYJ;
        this.FECHAINICIOMIYVIP = FECHAINICIOMIYVIP;
        this.FECHAINICIOMIYVI = FECHAINICIOMIYVI;
        this.FECHAINICIOSABADOD = FECHAINICIOSABADOD;
        this.FECHAINICIOSABADOD2 = FECHAINICIOSABADOD2;
        this.FECHAINICIOSABADOT = FECHAINICIOSABADOT;
        this.FECHAINICIOSABADOT2 = FECHAINICIOSABADOT2;
        this.FECHASPROHIBIDAS = new ArrayList<String>(FECHASPROHIBIDAS);
    }

}